# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          apt-get update && apt-get -y install r-base-core r-recommended
          install.packages('rmarkdown',repos='http://cran.rstudio.com')
          install.packages('tidyverse')
      - name: Build File
        run: |
          Rscript -e "rmarkdown::render('opendata_gs.Rmd', encoding="UTF_8")"
          mv opendata_gs.html index.html         
